import { wall, path } from './fields';

export const boards = [
  {
    enter: {
      row: 1,
      col: 0,
    },
    exit: {
      row: 29,
      col: 30,
    },
    grid: [
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
      [path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall],
      [wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall],
      [wall, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, path, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall],
      [wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, wall, path, wall],
      [wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, path],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
    ],
  },
  {
    enter: {
      row: 1,
      col: 0,
    },
    exit: {
      row: 29,
      col: 30,
    },
    grid: [
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
      [path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, path, path, wall],
      [wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
    ],
  },
  {
    enter: {
      row: 1,
      col: 0,
    },
    exit: {
      row: 29,
      col: 30,
    },
    grid: [
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
      [path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall],
      [wall, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall],
      [wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, wall],
      [wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall, path, wall, path, path, path, wall],
      [wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall],
      [wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
    ],
  },
];
