import { wall, path } from './fields';

export const boards = [
  {
    grid: [
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
      [path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall],
      [wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall],
      [wall, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, path, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall],
      [wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, wall, path, wall],
      [wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, path],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
    ],
  },
  {
    grid: [
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
      [path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall],
      [wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, path, path, wall],
      [wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall],
      [wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path, path, path],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
    ],
  },
  {
    grid: [
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
      [path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, wall],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, path, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall],
      [wall, path, wall, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall],
      [wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall],
      [wall, path, path, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, wall],
      [wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, path, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, wall],
      [wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall],
      [wall, path, wall, path, path, path, path, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, wall, path, wall, path, path, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, wall, path, wall, path, path, path, wall],
      [wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, wall, path, wall, path, path, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall, path, wall],
      [wall, wall, wall, path, wall, path, wall, wall, wall, wall, wall, path, wall, path, wall, path, wall, path, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall],
      [wall, path, path, path, wall, path, path, path, path, path, wall, path, path, path, wall, path, wall, path, wall, path, path, path, wall, path, path, path, wall, path, path, path, wall],
      [wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, path, wall, wall, wall, wall, wall, wall, wall, path, wall, path, wall, wall, wall, path, wall],
      [wall, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, path, wall, path, path, path, path, path, path],
      [wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall],
    ],
  },
];
